### ISSUE TITLE
stdio redirection not working under Windows 10?

### ISSUE THREAD

**Issue by TheGag96** [devkitPro/3dslink#8]
I've been using the latest 3dslink on my Artix Linux laptop with no issue. I set up a Windows 10 laptop with all the devkitPro tools tonight and tried 3dslink on it. Uploading the executable works just fine, but when my app launches and tries to redirect stdio, it just hangs forever, and the laptop does nothing after printing `server active ...`. Is there some configuration issue here or something else?

**Comment by WinterMute** [comment]
You'll most likely need to allow 3dslink through windows firewall, see https://pureinfotech.com/allow-apps-firewall-windows-10/

You should have got a popup the first time you used 3dslink but I think people quite often manage to close that dialog without noticing.

**Comment by TheGag96** [comment]
I will give this a try and report back! Thank you.

By the way, sorry to be a little off-topic, but would you mind taking a look at this forum thread I posted today, @WinterMute?

https://devkitpro.org/viewtopic.php?t=9492

It's another Windows-ism that didn't seem appropriate as a GitHub issue. Thanks!

**Comment by WinterMute** [comment]
The popup looks like this 
<img width="521" alt="image" src="https://github.com/devkitPro/3dslink/assets/101194/b5930c34-b704-4dd9-8046-77b7db5898f7">

**Comment by WinterMute** [comment]
And the cry of beleagured programmers everywhere ... works for me ;o) 

```davem@ashpool MSYS ~/projects/3ds/examples/network/3dslink-demo
$ 3dslink -s 3dslink-demo.3dsx
Sending 3dslink-demo.3dsx, 180648 bytes
82518 sent (45.68%), 8 blocks
starting server
server active ...
Hello World!

```

**Comment by TheGag96** [comment]
Lol right you are, that did the trick. I swear I never got that popup at all. Thanks!!
